name: ItemHandler
version: '${project.version}'
main: org.minecrafttest.main.ItemHandler
api-version: '1.20'
folia-supported: true
softdepend: [PlaceholderAPI, ProtocolLib]

commands:
  ItemHandler:
    description: Items from config File!
    usage: /itemhandler
    aliases:
      - ih
    permission: itemhandler.view