name: ItemHandler
version: '${project.version}'
main: org.minecrafttest.main.ItemHandler
api-version: '1.20'
folia-supported: true
softdepend: [PlaceholderAPI, ProtocolLib]

commands:
  itemHandler:
    description: Items from config File!
    usage: /itemhandler
    aliases: [ih]
    permission: itemhandler.view

  hologram:
    description: Spawn Hologram
    usage: /hologram <line1|line2|...>
    aliases: [holo]
    permission: hologram.spawn

permissions:

  hologram.spawn:
    description: Spawn Hologram
    default: true

  itemhandler.command.view:
    description: Allows the player to use the /hologram command
    default: true

  itemhandler.view:
    description: Allows the player to use the /itemhandler command
    default: true
  itemhandler.load:
    description: Allows the player to load items (general load)
    default: false
  itemhandler.load.only_me:
    description: Allows the player to load items only for themselves (load only_me)
    default: true
  itemhandler.reload:
    description: reload the plugins
    default: true