name: ItemHandler
version: '${project.version}'
main: org.minecrafttest.main.ItemHandler
api-version: '1.20'
folia-supported: true
softdepend: [PlaceholderAPI, ProtocolLib]

commands:
  ItemHandler:
    description: Items from config File!
    usage: /itemhandler
    aliases:
      - ih
    permission: itemhandler.view

permissions:
  itemhandler.view:
    description: Allows the player to use the /itemhandler command
    default: true
  itemhandler.load:
    description: Allows the player to load items (general load)
    default: false
  itemhandler.load.only_me:
    description: Allows the player to load items only for themselves (load only_me)
    default: true
  itemhandler.reload:
    description: reload the plugins
    default: true