items:
  clock:
    shotBow: false
    wear_armor: false
    material_change_interval_milliseconds: 2000
    materials:
      material1:
        sub_material: clock
      material2:
        sub_material: bow
      material3:
        sub_material: arrow
      material4:
        sub_material: iron_leggings
    quantity: 1
    slot: 0 # Inventory slot (0 for the first slot)
    name: '&eMenu de juegos &7(Click Derecho)' # Display name of the item
    set_drop: false # Whether the item can be dropped
    command_right: gmenu
    command_left: tps
    change_slot: false # Whether the item can change slot
    add_item_on_click: false

  vanish:
    material: GRAY_DYE
    materials:
      material1:
        sub_material: "%lobbyutils_blinded__GRAY_DYE__LIME_DYE%"
    quantity: 1
    slot: 7 # Inventory slot (1 for the second slot)
    name: "Jugadores: %lobbyutils_blinded__&cInvisibles__&eVisibles% &7(Click Derecho)" # Display name of the item
    set_drop: false # Whether the item can be dropped
    command_onclick: blind
    change_slot: false # Whether the item can change slot
    material_change_interval_milliseconds: 1
    #add_item_on_click: true

  star:
    material: NETHER_STAR
    materials:
      material1:
        sub_material: NETHER_STAR
    quantity: "%envman_LOBBY%"
    slot: 8 # Inventory slot (1 for the second slot)
    name: "Selector de Lobbys &7(Click Derecho)" # Display name of the item
    set_drop: false # Whether the item can be dropped
    command_onclick: lobbys
    change_slot: false # Whether the item can change slot
    material_change_interval_seconds: 1
    #add_item_on_click: true